---
title: "数据探索分析"
author: 谢国伟
execute: 
    echo: false
    message: false
    warning: false
knitr:
    opts_chunk: 
      dev: "ragg_png"
format:
    pdf: 
        toc: false
        number-sections: false
        CJKmainfont: STKaiti
        df-print: kable
        fig-width: 8
        fig-height: 5

editor_options: 
  chunk_output_type: console
 
---





```{r setup}
library(tidyverse)
library(gt)
library(reshape2)
library(factoextra)
library(fmsb)
library(jsonlite)
```


```{r data}
codes <- read.csv("Datasets/codes.csv")
displays <- read.csv("Datasets/displays.csv")
values <- fromJSON("Datasets/values.json")
values <- as.data.frame(values[["data"]])


dat <- codes %>% 
    left_join(displays, by = c("gho_code" = "gho_code",
                               "country_code" = "country_code",
                               "region_code" = "region_code",
                               "sex_code" = "sex_code",
                               "world_bank_income_group_group_code" = "world_bank_income_group_group_code"
                               )) %>%
    left_join(values, by = c("id" = "id"))
```

1. 根据最新数据（2013），统计各个地区 (region) 的 60岁时预期寿命区间 
```{r tbl_1}
dat %>%
    filter(gho_display == "Life expectancy at age 60 (years)",
           year_code == "2013") %>% 
    group_by(region_display) %>% 
    summarise(
        Min = min(value, na.rm = TRUE),
        Max = max(value, na.rm = TRUE)
    ) %>% 
    ungroup %>% 
    select(region_display, Min, Max) %>% 
    gt() %>% 
    cols_label(
        region_display = "region"
    )
```

2. 根据1990年的数据，统计了各个国家男女性别在 出生时预期寿命 上的差距，由高到低排序。
列出排名前三（差距最大）与倒数前三（差距最小）的国家。
```{r tbl_2}
diff_sort <- dat %>% 
    filter(year_code == "1990",
          gho_display == "Life expectancy at birth (years)" ) %>% 
    group_by(country_code, country_display) %>% 
    summarise(
        Female = sum(ifelse(sex_code == "FMLE", value, 0)),
        Male = sum(ifelse(sex_code == "MLE", value, 0)),
    ) %>% 
    ungroup() %>% 
    mutate(Diff = abs(Female - Male)) %>% 
    arrange(desc(Diff))

# 前三名
diff_sort_top3 <- diff_sort %>% 
    head(3)

# 后三名
diff_sort_last3 <- diff_sort %>% 
    tail(3)

rbind(diff_sort_top3, diff_sort_last3) %>% gt()
    
```

3. 不区分性别，针对东亚区域 (South_East Asia) ，对比男女在 出生时预期寿命 以及 60岁时预期寿命 的差距。（请尝试利用图表表达，如图1）
```{r plt1}
m_dat <- dat %>% 
    filter(region_display == "South_East Asia",
           gho_display %in% c("Life expectancy at birth (years)", "Life expectancy at age 60 (years)")) %>% 
    group_by(gho_display) %>% 
    summarise(m_value = mean(value, na.rm = TRUE))


dat %>% 
    filter(region_display == "South_East Asia",
           gho_display %in% c("Life expectancy at birth (years)", "Life expectancy at age 60 (years)")) %>% 
    group_by(country_display, gho_display) %>% 
    summarise(
        Female = mean(ifelse(sex_code == "FMLE", value, NA), na.rm = TRUE),
        Male = mean(ifelse(sex_code == "MLE", value, NA), na.rm = TRUE),
    ) %>% 
    ungroup() %>% 
    left_join(m_dat, by = "gho_display") %>% 
    ggplot() +
    geom_vline(xintercept = 1, linetype='solid')+
    geom_vline(xintercept = 2, linetype='solid')+
    geom_point(aes(x = 1, y = Female), color = "lightblue", size = 2)+
    geom_point(aes(x = 2, y = Male), color = "lightblue", size = 2)+
    geom_segment(aes(x=1, xend=2, y = Female, yend= Male), size = .3)+
    geom_text(aes(x = 1, y = 1, label = "Female"))+
    geom_text(aes(x = 2, y = 1, label = "Male")) +
    geom_hline(aes(yintercept = m_value), lty = 4, col = "salmon")+
    facet_grid(~ gho_display)+
     labs(
        x = ""
    )+
    theme(axis.title.x = element_blank())

```

4. 扩展第三道题目，比较1990年至2013年间各个东亚国家在出生时预期寿命方面的进步情况（如图2）。
```{r plt2}

dat %>% 
    filter(region_display == "South_East Asia",
           gho_display == "Life expectancy at birth (years)",
           year_code %in% c("1990","2013")) %>% 
    group_by(country_display, year_code) %>% 
    summarise(
        m_value = mean(value)
    ) %>% 
    ungroup() %>%
 
    ggplot(aes(x = m_value, y = country_display, color = year_code))+
    geom_point()+
    geom_line()+
    labs(
        x = ""
    )
    


```





